### ISSUE TITLE
HasRawWindowHandle for RawWindow fails on some platforms

### ISSUE THREAD

**Issue by parasyte** [Lokathor/beryllium#108]
This was originally reported in https://github.com/parasyte/pixels/issues/53

`raw_window_handle` panics on some platforms (which I cannot reproduce) when `SDL_GetWindowWMInfo` fails. The reported error is:

> Application not compiled with SDL 2.0

Which I was able to track down to an issue with the way `SDL_GetWindowWMInfo` is called. According to the [libsdl wiki](https://wiki.libsdl.org/SDL_GetWindowWMInfo#Remarks):

> The **info** structure must be initialized with the SDL version, and is then filled in with information about the given window, as shown in the [Code Example](https://wiki.libsdl.org/SDL_GetWindowWMInfo#Code_Examples).

This suggests that `beryllium` needs to populate the `SDL_SysWMinfo` struct with the SDL version _at a minimum_. The default impl just zeros the struct: https://github.com/Lokathor/beryllium/blob/cfdd6a3e14b0b71b5dda1718e1826d815d41e3fd/src/window/raw_window.rs#L49-L50

**Comment by Lokathor** [comment]
@parasyte I've pushed the change to the `master` branch, but you should have folks test the change before i push out a new version to crates.io

**Comment by parasyte** [comment]
Got confirmation that this works! 🎉

@Lokathor :shipit:

**Comment by Lokathor** [comment]
0.3.2 is out
