### ISSUE TITLE
Allow SDL window to be resized

### ISSUE THREAD

**Issue by Bricklou** [Lokathor/beryllium#110]
Hello,

After some search in the source code, I didn't found a way to allow my SDL window to be resized by the user. Is there something implemented to do that ?

**Comment by Lokathor** [comment]
At the moment no. It would be a fairly simple PR to add, you'd just need to add a method that calls `SDL_SetWindowSize`

**Comment by Bricklou** [comment]
I'll will try to look at it. (I'm working with the version 0.3.2)
