### ISSUE TITLE
Uninformative error on audio error

### ISSUE THREAD

**Issue by ZetaTwo** [Lokathor/beryllium#113]
My environment: 
Ubuntu 21.04 VM running in VMWare Workstation
Rust version: rustc 1.58.0-nightly (d914f17ca 2021-11-16)

Running a minimal example like this:

```rust
...

fn main() -> SdlResult<()> {
  let sdl = Sdl::init(InitFlags::AUDIO)?;
  Ok(())
}
```

Creates an empty SdlError like this:

```bash
$ cargo run
Finished dev [unoptimized + debuginfo] target(s) in 0.04s
Running `target/debug/game_playground`
Error: SdlError("")
```

However, using a flag set with all flags except audio like this:

```rust
fn main() -> SdlResult<()> {
  let sdl = Sdl::init(InitFlags::EVERYTHING & !InitFlags::AUDIO)?;
  Ok(())
}
```  

works fine so it is specifically something with the audio init that is not working, however it is a bit difficult to troubleshoot with an empty error like this.

**Comment by Lokathor** [comment]
Near as I can tell, all parts of `beryllium` itself that make their own error do not generate blank messages.

This means that the error is coming from SDL2 itself, but SDL2 isn't setting an error message before `SDL_Init` returns.

You might want to find a sample SDL2 program in pure C and build it and try it. If it also has problems then you can file an issue in the [SDL2 github itself](https://github.com/libsdl-org/SDL).

If the pure C version does *not* error, and the Rust version does, then that's suspicious and we'll have to investigate more deeply.

**Comment by ZetaTwo** [comment]
Yeah that makes sense. I should have tried that before reporting. Anyway, I tried creating a minimal SDL program similar to the Rust example above like this:

```c
#include <SDL2/SDL.h>

int main() {
    int sdl_error = SDL_Init(SDL_INIT_EVERYTHING); // or SDL_INIT_AUDIO
    printf("SDL Init res: %d, error: \"%s\"\n", sdl_error, SDL_GetError());
}
```

Compiling and running gives no error:
```bash
$ gcc -o test1 test1.c -lSDL2
$ ./test1
SDL Init res: 0, error: ""
```

I also tried narrowing it down by calling the fermium function directly:

```rust
...
fn main() -> () {
    unsafe {
        let sdl_res = fermium::SDL_Init(fermium::SDL_INIT_AUDIO);
        println!("SDL res: {}", sdl_res);
    }
}
```

and this also gives an error:

```bash
$ cargo run
SDL res: -1
```

I tried this with both SDL 2.0.12 and 2.0.16 as I couldn't really figure out which one the crate is supposed to be using.

**Comment by Lokathor** [comment]
Well `fermium` is using a bundled 2.0.16.

My next guess is that the bundled build of SDL2 is not using the correct configuration or something like that compared to your system SDL2, and so it's having the problem when your system SDL2 isn't.

**Comment by ZetaTwo** [comment]
Do you have any suggestions for steps I can take to troubleshoot this more thoroughly and provide some better information?

**Comment by Lokathor** [comment]
So I think, you can clone fermium: https://github.com/Lokathor/fermium
build the SDL2 in the `SDL2-2.0.16` folder, and then link against that to see if it's having the error.

```
git clone git@github.com:Lokathor/fermium.git
cd fermium/SDL2-2.0.16
mkdir build
cmake -S . -B build
cd build
make
```
Then try your demo program but link against that build of SDL2.

**Comment by ZetaTwo** [comment]
Ok. Versions didn't seem to matter but I am slightly closer to something now. I noticed that my compiled C program had way more libraries dynamically linked compared to the Rust version so I searched around for how to statically link those libraries and by compiling the program like this:

```bash
$ gcc -o test1 test1.c -Wl,-Bstatic -lSDL2 -Wl,-Bdynamic -lm -ldl -lpthread -lrt
$ ./test1
./test1
SDL Init res: -1, error: ""
```

I get the same error state as the Rust program.
Looking at the strace of the program I see 

```
newfstatat(AT_FDCWD, "/dev/sound", 0x7ffead7417d0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/dev/dsp", 0x7ffead7417d0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/dev/dsp0", 0x7ffead7417d0, 0) = -1 ENOENT (No such file or directory)
...
newfstatat(AT_FDCWD, "/dev/dsp63", 0x7ffead7417f0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/dev/dsp64", 0x7ffead7417f0, 0) = -1 ENOENT (No such file or directory)
```

Running the Rust program with strace gives a very similar output. If I instead link SDL dynamically like before I see a lot of references to pulseaudio in the strace logs so it seems that either SDL or pulse audio or something related is not playing nice with the static linking. Unfortunately, I am not at all an expert on Linux sound to understand why this happens.

**Comment by Lokathor** [comment]
I am also not an expert, but my experience has been that if you dynamically link on unix the binary becomes sensitive to the relative path between the library and the executable. I believe that the `dynamic_link` cargo feature of fermium does build fine, but the generated binaries aren't portable to other unix systems, which is why it's marked as "not working" inside the Cargo.toml for fermium.

**Comment by ZetaTwo** [comment]
I don't think that is true, although you will of course have SDL installed on the system. I tried building with:

```toml
[dependencies.fermium]
version = "20016.0.0"
features = ["dynamic_link"]
```

and the output of `ldd` looks fine,

```bash
$diff <(ldd ./test1-dynamic|awk '{print $1}'|sort) <(ldd ../rust-game-engine/target/release/game_playground|awk '{print $1}'|sort)
15a16
> libgcc_s.so.1
```

and I can copy the binary around to and directory and it works fine. What suggested that it becomes sensitive to the relative path? I would suggest switching to dynamic linking as that is also the recommendation by SDL themselves.

Something that's a bit weird though is that if I run the binary itself with:
```bash
$ ./target/debug/game_playground
```

it works fine but if I run it with 
```bash
$ cargo run
```

it gives an error.

**Comment by Lokathor** [comment]
It's been quite a while since I last worked on this error, I don't remember it super well. I think the issue was if you built with the bundled SDL2 and then moved the program to another machine then the binary wouldn't be able to find the system SDL2 on the new machine. Similarly if you build and then get the binary out of the target directory and then delete that target directory and try to run the program.

Though if the problem has gone away on its own somehow I guess that would be great too.

**Comment by ZetaTwo** [comment]
Yeah I was not able to reproduce that issue and I also tried using rust-sdl2 which does not have this issue either and they do dynamic linking. If you want me to try something specific, I will gladly help out but other than that I probably won't spend more time on this issue.

**Comment by Lokathor** [comment]
Alright, well if dynamic linking is working great right now that's fine enough I suppose. Should we close this issue?

**Comment by ZetaTwo** [comment]
Feel free to close the issue.

For anyone reading this in the future: there seems to be something strange with static linking and audio on Linux, at least in my particular setup.
