### ISSUE TITLE
Re-implement raw-window-handle?

### ISSUE THREAD

**Issue by parasyte** [Lokathor/beryllium#114]
Since the rewrite, `raw-window-handle` is no longer supported.

**Comment by Lokathor** [comment]
oh yeah, this would be a good idea.

**Comment by Lokathor** [comment]
Alright, so in https://github.com/Lokathor/fermium/commit/7cff0fd3efc82a84f5f9095e7d644ab20ced5af6#diff-734ab7743dd3366691ab07617b15575e5743e0ee0987b7b9d8e7a219b200d7a8 I added `fermium` level support for converting SDL2's info into the raw-window-handle info, and if that looks correct I'll publish an actual release of fermium with that, and then beryllium can just call the function and use that converstion.

**Comment by parasyte** [comment]
It looks like this implementation will have the same problem as the one described in https://github.com/Rust-SDL2/rust-sdl2/issues/1116 and https://github.com/gfx-rs/wgpu/issues/1500

I tried to prototype how I would use this (currently testing on Windows 11) and ran into the issue that `RawWindowHandle` does not implement the `HasRawWindowHandle` trait. So I created a newtype:

```rust
struct Rwh(RawWindowHandle);

unsafe impl HasRawWindowHandle for Rwh {
    fn raw_window_handle(&self) -> RawWindowHandle {
        self.0
    }
}
```

What I ended up with (using just fermium) is basically this:

```rust
let mut pixels = {
    let mut width = 0;
    let mut height = 0;
    let rwh = unsafe {
        let mut window_info = SDL_SysWMinfo::default();
        assert_eq!(SDL_GetWindowWMInfo(window, &mut window_info), SDL_TRUE);
        SDL_GetWindowSize(window, &mut width, &mut height);

        Rwh(window_info.try_into().unwrap())
    };

    let surface_texture = SurfaceTexture::new(width as u32, height as u32, &rwh);
    Pixels::new(WIDTH, HEIGHT, surface_texture)?
};
```

All said, it works, but it's weird having to create a newtype to get the trait impl.

**Comment by aegroto** [comment]
Is there any workaround for this until this feature is implemented again? My project [remotia](https://github.com/aegroto/remotia) is relying on a rev version of beryllium, 0.3.2 and 0.3.3 still fail on my machine (I'm running Mesa drivers on AMD) and I guess 0.4.0 is an already reworked version that do not implement the raw-window-handle feature.

**Comment by Lokathor** [comment]
oh, uh, i can finish and publish the change probably later today.

given that the latest version of things probably lacks other elements too I'm not entirely sure you want to upgrade immediately anyway, but i think I can sort out the raw window handle thing pretty quick.

**Comment by Lokathor** [comment]
Alright, 0.7.6 should have `raw-window-handle` support under the slightly unfortunate alternate name `use-raw-window-handle`.

Since turning on raw-window-handle in beryllium requires that we turn it on in fermium, and since a feature can't be named the same as an optional dep, and since namespaced deps and features are nightly only, this is the universe we get.

But, again, I'd like to stress that most likely no one should actually use this crate. Even I don't particularly use this crate. It is chronically incomplete.

**Comment by parasyte** [comment]
> It is chronically incomplete.

Can confirm!
