### ISSUE TITLE
Cannot (easily) store SDLToken, Window, GLcontext in same struct

### ISSUE THREAD

**Issue by thomcc** [Lokathor/beryllium#53]
I'd like to be able to store my main loop state in a structure to make it a little cleaner, and share code (between a game and editor window in my case). The lifetime params on `Window<'sdl>` and `GLContext<'sdl, 'win>` makes it very painful to do this.

This can be done in a few ways with unsafe (either using something like `rental`, which has a bunch of restrictions and is annoying to use), or just transmuting the lifetimes to `'static` and making sure that you maintain the invariants they enforced (this is what I did).

Both of these solutions extremely suck, since this case seems likely to be common to me (most games I've seen did things not that differently from this. The only other common pattern is just keeping it all as separate variables on the stack which is awkward and limiting).

I feel like this is making the common case hard in favor of more niche use cases like initializing SDL multiple times (as opposed to just ensuring SDL_Quit is called exactly once), or multiple windows (which is certainly less niche, but still more niche than having just one window). Ideally the balance could be shifted in the other direction (I know you hate Rc<T> but it *is* one option here, but not the only one)

**Comment by Lokathor** [comment]
Well, you can't even initialize SDL2 more than once with this lib.

I don't think I'll add Rc in to all sorts of things, but I'd certainly be willing to expand the `gl` example to have a "combination" struct like `glium` example has.

Personally I do the "keep it all separate on the stack", but I have sympathy for the other style folks.
